version: '3.8'

services:
  oracle-free:
    image: gvenzl/oracle-free
    container_name: oracle-free
    ports:
      - "1521:1521"   # Puerto para conexi√≥n SQL
      - "5500:5500"   # Oracle Enterprise Manager
    environment:
      - ORACLE_PASSWORD=Oracle123
      - APP_USER=appuser         # usuario adicional opcional
      - APP_USER_PASSWORD=app123
    volumes:
      - oracle-data:/opt/oracle/oradata   # Persistencia de datos
    restart: unless-stopped

volumes:
  oracle-data:
